### ISSUE TITLE
Doenst run on Windows 10 21H2

### ISSUE THREAD

**Issue by ottemomo** [KJ-black/windows-knock#1]
When i run it on Windows 10 21H2 i got these error message:

- C:\Users\ottemo\Downloads\windows-knock-main>python knockd.py
- Traceback (most recent call last):
-   File "C:\Users\ottemo\Downloads\windows-knock-main\knockd.py", line 192, in <module>
-     port_knockd()
-   File "C:\Users\ottemo\Downloads\windows-knock-main\knockd.py", line 184, in port_knockd
-     w.send(packet)
-   File "C:\Users\ottemo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pydivert\windivert.py", line 236, in send
-     windivert_dll.WinDivertSend(self._handle, buff, len(packet.raw), byref(packet.wd_addr),
-   File "C:\Users\ottemo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pydivert\windivert_dll\__init__.py", line 54, in wrapper
-     raise err
- OSError: [WinError 87] Falscher Parameter.

Python 3.10.9
pip 22.3.1

**Comment by KJ-black** [comment]
I was using python 3.7 for programming. After some attempts for changing different environments and host settings. I found out that there seem to have some bugs for python 3.10 to run pydivert. I will try to find out what makes it an error in 3.10 when I have time. Thanks for your comments. I will add my testing environment info to the readme.
